### ISSUE TITLE
Mweb: Menu: Incorrect background color for search button

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#12]
Description:
The search icon/button has a black background. The correct color would be #00A5B5

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156376751-bfdcaeed-d668-4dd8-afb6-0ee888aed002.png)

**Comment by mrnarvekar** [comment]
This issue is already fixed and looks to be cache issue.

**Comment by ShivaniAjency** [comment]
Done
