### ISSUE TITLE
Mweb: Explore article: Padding issue for the Horizontal Tab

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#13]
Description:
Top and bottom padding is improper for the horizontal tab

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156377570-88a94269-d883-49d0-8616-d0b769c2582e.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Done
