### ISSUE TITLE
Mweb: Footer: Subscribe button

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#14]
Description:
The button color for subscribe button is incorrect. The correct color would be #00A5B5

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156378516-264dce44-ecca-494d-8016-d3c47eb9d807.png)

**Comment by mrnarvekar** [comment]
Duplicate issue

**Comment by ShivaniAjency** [comment]
Fixed
