### ISSUE TITLE
Header: menu: On hovering the menu item you get a grey background

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#16]
Description:
 On hovering over the menu item you get a grey background. On the reference site, you do not get menu items do not get a background color on hovering:

Screenshot:
https://www.awesomescreenshot.com/video/7697028?key=6103b32f907b345b7acb5bcf9664d7e2

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
