### ISSUE TITLE
Footer: Footer logo: UI Issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#19]
Description:

1. Footer logo looks too big. The ideal height as per design should be 36px
2. Footer logo is not in alignment with the footer menu title

Screenshot:
1) 

![image](https://user-images.githubusercontent.com/75774252/156556419-f103d4e9-13b1-43ae-af1c-261cb9262cfb.png)

2)
Design
![image](https://user-images.githubusercontent.com/75774252/156556569-8c576535-b6eb-49af-8931-7ad54613200c.png)

Site
![image](https://user-images.githubusercontent.com/75774252/156556689-c0e9cd06-c530-4653-8d77-3eb2df5b47a7.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
