### ISSUE TITLE
Categories: Remove Healthcare category 

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#2]
Description:
As per the document shared it has been clearly stated to remove the healthcare category.

![image](https://user-images.githubusercontent.com/75774252/156163418-feb89a33-d67c-4f55-89dd-3c613ecb764b.png)

However, in the Wordpress backend this category is present

![image](https://user-images.githubusercontent.com/75774252/156163553-526fb701-93e3-4301-aa70-44e260e10571.png)

**Comment by mrnarvekar** [comment]
Done. Removed the category

**Comment by ShivaniAjency** [comment]
Fixed
