### ISSUE TITLE
Footer: Cash on delivery logo is getting cropped

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#20]
Description:

Cash on delivery  logo is getting cropped

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156560427-3a0b055d-a994-4231-a6c2-cb01f487c15c.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
