### ISSUE TITLE
Footer: Get to know us: Line height issue

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#21]
Disclaimer:
Line height should be 30px

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156563719-ca599c1d-ebce-4054-bfd9-56c249b6acfb.png)

Screenshot after setting line-height to 30px
![image](https://user-images.githubusercontent.com/75774252/156563930-64626e13-804f-49ab-8f50-2ce27a796a08.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
