### ISSUE TITLE
Footer: Top margin is missing

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#22]
**Description:**

The top margin is missing and hence logo and text have no space between them. The top margin should be 12px

**Screenshot:**
![image](https://user-images.githubusercontent.com/75774252/156566218-d3dca89f-8bbb-42c7-928a-06b790092d30.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
