### ISSUE TITLE
Favicon is getting cropped

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#23]
Description:
The Favicon on our site looks cropped. (pointed blue arrow)

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156740271-1031a8ca-6cda-4a3a-9ff9-1236d516f2fd.png)
![image](https://user-images.githubusercontent.com/75774252/156740708-74b4cbb5-b21f-4b14-8faa-cd6bfc75cc62.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check.

**Comment by ShivaniAjency** [comment]
Fixed
