### ISSUE TITLE
Search bar: Firefox: Placeholder not visible

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#24]
Description:
The placeholder text in firefox is white and cannot be read. It should be 9E9E9E

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156743016-1fc4f09b-2340-4e56-bd21-31b6f6063923.png)

It should be:
![image](https://user-images.githubusercontent.com/75774252/156743088-669d321d-e20a-4915-9baa-51e816a97c5e.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
