### ISSUE TITLE
Latest & Trending Articles: UI Issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#25]
Description:

1. Please keep the post title up to 2 lines otherwise it abrupts the UI on the smaller screen
2. The same issue has been seen on mac and firefox as well

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156747826-85dea7a3-57f2-42fd-ad5e-2f5986a15a05.png)

![image](https://user-images.githubusercontent.com/75774252/156748418-df161b51-fc04-41cb-861d-574b476112e3.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
