### ISSUE TITLE
Explore articles UI issue

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#27]
Description:

No space between the article container and the view more button. The same issue was seen in Firefox

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156750642-55b5e09e-b655-4d55-9270-e961f76d89ef.png)

**Comment by mrnarvekar** [comment]
Done. Kindly test

**Comment by ShivaniAjency** [comment]
Fixed
