### ISSUE TITLE
MAC OS: More Articles: Space issue between excerpt and pagination 

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#28]
Description:

There is little/ no space between the excerpt text and pagination.

Screenshot:
Macbook air
![image](https://user-images.githubusercontent.com/75774252/156752108-bbd54d57-3b81-415c-947c-f6fb0f0c5df6.png)

Windows:
![image](https://user-images.githubusercontent.com/75774252/156752177-633e8bb1-d0dd-4e89-9c97-7be4d2895e31.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check
![MAC OS carousel](https://user-images.githubusercontent.com/89069801/156981105-e915574d-55c4-4ccf-bd38-7976778d9720.PNG)

**Comment by ShivaniAjency** [comment]
fixed
