### ISSUE TITLE
Firefox: Footer: Subscribe form: Incorrect placeholder color

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#29]
Description:
The placeholder color is incorrect. It should be 9E9E9E

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156753074-54ef76c8-4e73-452c-85ee-53cd6d2872ff.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
