### ISSUE TITLE
IOS:Mobile:Footer: Dropdown is not expanding

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#30]
Description:
Unable to expand/open the dropdown

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156756927-13a7dc24-8661-4464-b96b-03fe5e6d6ebc.png)

**Comment by mrnarvekar** [comment]
Issue is not replicating on IOS. Kindly retest on IOS and update
![Web capture_7-3-2022_115143_live browserstack com](https://user-images.githubusercontent.com/89069801/156979007-0ac78cc6-3ab5-4fa5-a7b9-106263a9fd10.jpeg)

**Comment by ShivaniAjency** [comment]
Wotking fine
