### ISSUE TITLE
Logo: UI Issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#31]
Description"

1. The Logo on the homepage for mweb looks big. On the reference site the hamburger menu and the bottom are on the same line. (height is 38)
![image](https://user-images.githubusercontent.com/75774252/157009158-55a0f164-33f9-4be1-b827-dae47c251cd5.png)
![image](https://user-images.githubusercontent.com/75774252/157010085-ff06cd25-6ab1-4a66-b739-e95a0d3a7a81.png)

After doing the changes in inspect mode
![image](https://user-images.githubusercontent.com/75774252/157009933-f49c384b-d97f-4878-8c1e-3670648dbf33.png)

2. Logo Does not load on MacBook Air and iPhone 8
![image](https://user-images.githubusercontent.com/75774252/157009411-e9a42ec9-3acd-4faa-bfe7-3647a8a39bf7.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
