### ISSUE TITLE
Mweb Menu: the mweb menu should not have border

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#32]
Description:
The mweb menu should not have a border.

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157023623-712b4931-80c4-471f-a861-05e027cf2ad1.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
