### ISSUE TITLE
Single Blog Post page: Breadcrumps: No space between the breadcrumbs and the header menu

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#33]
Description:
No space between the breadcrumbs and the heading. Same issue has been seen in firefox

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157029656-30762df3-7310-4bba-9c9f-0417b93a3af9.png)
![image](https://user-images.githubusercontent.com/75774252/157029734-bd9b93e5-81bc-4d12-8fd3-961a716117b0.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
