### ISSUE TITLE
MacBook Air: Single blog Post: Breadcrumbs are not visible

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#34]
Description:
The Breadcrumbs in Mac book air are not visible

Screenshot:
![Screenshot 2022-03-07 at 5 27 18 PM](https://user-images.githubusercontent.com/75774252/157030492-87e5d9b1-8fa3-46f6-97d1-8e81e0bd42b3.png)

**Comment by mrnarvekar** [comment]
Issue is not related MAC book or OS, but is related to old version of Safari. Issue is there on Safari 13.1 but on 14.1 and latest Safari version issue doesnt exists. Kindly update the Safari browser and test. Attaching screenshot.

Safari 13.1
![safari 13 1](https://user-images.githubusercontent.com/89069801/157424290-3f8ba51c-c7a4-44c4-b7f6-628b8c51ca1e.PNG)

Safari 14.1 - Issue not happening
![Safari 14 1](https://user-images.githubusercontent.com/89069801/157424333-cb00e0ef-ee1f-499c-9570-5253a82e56e6.PNG)

**Comment by ShivaniAjency** [comment]
Tested on safari 15.3. Issue fixed
