### ISSUE TITLE
Category page: UI Issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#36]
Description:

1. There is no space between the header menu and the breadcrumbs
2. There is no space between the articles tiles.

Description:
![image](https://user-images.githubusercontent.com/75774252/157231377-16a0fb8f-f9d5-4176-b5c3-3ba85b629599.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
