### ISSUE TITLE
Category page: UI Issues Mac Os

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#37]
Description:

1. On loading the category page the breadcrumbs get hidden.
2. There are is no space between the article tiles

Screenshot:
1)
![image](https://user-images.githubusercontent.com/75774252/157232286-78536eb4-a828-443f-9903-b51aebaae54a.png)

2)
![image](https://user-images.githubusercontent.com/75774252/157232597-577c221b-c508-41b4-bc1a-7b438a21b3b6.png)

**Comment by ShivaniAjency** [comment]
This was tested on MacBook air, safari version 13.1

**Comment by mrnarvekar** [comment]
This issue is related to Safari 13.1 and less. Issue not happening on the latest Safari version. Attaching screenshot of Safari 14.1
![Safari 14 1](https://user-images.githubusercontent.com/89069801/157424811-d940ec88-3130-4247-acbe-e5174503615b.PNG)

**Comment by mrnarvekar** [comment]
Space between articles title issue, is fixed. Kindly test

**Comment by ShivaniAjency** [comment]
Fixed
