### ISSUE TITLE
Mweb: Tag: UI Issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#38]
Description:

1. The article tiles are loading more than once
2. If we scroll down towards the footer, then we get the loading content sign.

The issue was detected in Samsung galaxy m31 prime and iPhone 8

The second issue was also seen on the category page

Screenshots:
![5b35d912-47ab-4650-8992-7b7789f1f598](https://user-images.githubusercontent.com/75774252/157422275-7c67d474-87c0-4ae7-bbc9-a0f2b83f9ade.png)

https://drive.google.com/file/d/1VSeIWLJuEIVYSjFdZs5L368JHag7Cz2E/view?usp=sharing

https://drive.google.com/file/d/1mpYLqW94cG-BkfZcwhqe_yLothMxxV9J/view?usp=sharing

**Comment by mrnarvekar** [comment]
This is working as per the functionality as same functionality has been implemented for healthkart.com and truebasics. Check healthkart.com -> https://www.healthkart.com/connect/hair-skin-and-nails/nutrition-for-nails/

**Comment by ShivaniAjency** [comment]
Noted
