### ISSUE TITLE
Author page: There is no gap between the article tiles

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#39]
Description:
There is no gap between the article tiles. This issue was also seen in mac

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157424973-672b68ac-3d81-4ef0-bf90-b72c16651998.png)

reference site:
![image](https://user-images.githubusercontent.com/75774252/157425091-9bbf4aef-f56a-4764-b35a-d5d24b3706a3.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Issue fixed
