### ISSUE TITLE
Tags: Tags are missing

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#4]
Description:
Some tags are missing on the Wordpress site. they are listed as below:

- Bones 
- Calcium
- Fish oil

Screenshot:
1) From the live
![image](https://user-images.githubusercontent.com/75774252/156167302-9040b440-70fa-4fd8-84b1-af5b729af644.png)

2) Wordpress
![image](https://user-images.githubusercontent.com/75774252/156167358-349436dc-74f2-4167-87ff-2ce3d6b746aa.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check.

**Comment by ShivaniAjency** [comment]
Fixed
