### ISSUE TITLE
mweb: Menu should not have a shadow

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#40]
Description:
The mweb menu should not have a shadow.

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157429497-611c3d89-7807-40e4-ae86-fe672f313703.png)

Reference:
![image](https://user-images.githubusercontent.com/75774252/157429580-19530768-0dad-4421-8c96-4205096349ed.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check
