### ISSUE TITLE
Tab:Single blog post page: what to read next: UI issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#41]
Description:

- No space between the article tiles
- Title starts on different lines

Dimension: 768*711

![image](https://user-images.githubusercontent.com/75774252/157434964-9f014202-93b0-4c02-8dea-67a6dd8b7002.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
