### ISSUE TITLE
Tab: Category page:  The article tabs get repeated

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#42]
Description:
The article gets repeated

![image](https://user-images.githubusercontent.com/75774252/157435381-b2097de8-a609-46d9-8a9b-c8eee84edc5c.png)

**Comment by mrnarvekar** [comment]
This is working as per the functionality as same functionality has been implemented for healthkart.com and truebasics. Check healthkart.com -> https://www.healthkart.com/connect/hair-skin-and-nails/nutrition-for-nails/

**Comment by ShivaniAjency** [comment]
Noted
