### ISSUE TITLE
Tab & Mweb : Logo looks stretched 

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#43]
Description:
The logo in the tab view looks stretched

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157638489-34812b43-2dc5-4e28-9ada-7210834f32e1.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Issue fixed
