### ISSUE TITLE
Mweb Menu: UI Issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#44]
Description:
The menu items should be vertically in line with the search box

Screenshot:

Site
![image](https://user-images.githubusercontent.com/75774252/157639936-51f3090e-71c0-40c9-87b1-7153dd6d2228.png)

Reference:
![image](https://user-images.githubusercontent.com/75774252/157640216-cb3dc1e5-390f-44a3-86ac-ab120f79cf72.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Issue fixed
