### ISSUE TITLE
No search result: Missing border for the pop-up

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#45]
Description:
When the search item is not present a popup loads. The border and the border of the same is missing on the site

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157641616-ec24b43e-aab2-4828-ac82-4784cb6734a0.png)

Ref:
![image](https://user-images.githubusercontent.com/75774252/157641657-0fa1c45e-cfc8-4a21-b6c3-c70f061e75b2.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Done
