### ISSUE TITLE
Logo: Improper padding between the logo and the image slider

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#46]
Description:

1. Improper padding between the logo and the image slider. 
2. The space between the slider and the logo looks less compared to the reference site. 
3. In the design shared the spacing between the menu and the logo is 16px

Screenshot:
1
![image](https://user-images.githubusercontent.com/75774252/157843668-306d5f5c-42e8-491f-b568-069eecdeca6c.png)

2.

![image](https://user-images.githubusercontent.com/75774252/157843789-3f293951-6864-452b-a297-daf4781ecdac.png)

3

![image](https://user-images.githubusercontent.com/75774252/157843857-37f3ca34-c018-4240-909f-563ab28348fc.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Issue fixed
