### ISSUE TITLE
Homepage: Articles Sliders: Excerpt should be upto two lines

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#47]
Description:
The excerpt should be up to 2 lines

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157848102-94b8adef-3e63-4d3f-87c5-eb5196ece17d.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Implement for mweb

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
issue fixed
