### ISSUE TITLE
Explore articles: All categories do not get displayed

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#48]
Description:
Under the explore more section all the categories do not get displayed

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157850021-058aad5a-6fbd-40ae-bfb4-da48b8004443.png)

![image](https://user-images.githubusercontent.com/75774252/157850121-4b02dc2e-b2b8-42d7-8541-499bd5e3cb51.png)

**Comment by mrnarvekar** [comment]
Since other categories are not having any post. Only 3 categories are shown

**Comment by ShivaniAjency** [comment]
I created a test post and have added it to the Hair and Skin Care category. The checkbox was also checked in. However, the category tab did not get displayed.

Is this coming from the code? or Can I edit this from the Wordpress backend?

**Comment by mrnarvekar** [comment]
You can add from category setting in wordpress

**Comment by ShivaniAjency** [comment]
Got it
