### ISSUE TITLE
Footer: Subscribe for updates: Field is not validated

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#49]
Description:
The subscribe for updates field is not validated

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157851890-3b8c9301-37ec-41bd-ad85-520a398ff706.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
fixed
