### ISSUE TITLE
Footer: Menu heading should be vertically center aligned

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#50]
Description:
Menu heading should be vertically center aligned

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157854187-771e5f6d-e8ed-4dea-836e-205c5d74d1ee.png)

Design:
![image](https://user-images.githubusercontent.com/75774252/157854605-cd42fb8d-d836-4b75-853a-bc7a0e72d704.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Fixed
