### ISSUE TITLE
Explore more: 6 articles should get displayed

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#51]
Description:

- 6 articles should get displayed for a particular category
- Muscle, Bone, and Joint Health has more than 6 articles yet only 3 get displayed

screenshot:
![image](https://user-images.githubusercontent.com/75774252/157865150-c8a3b1bd-f49c-460f-82ce-406c04ea820b.png)

![image](https://user-images.githubusercontent.com/75774252/157865279-879d53d2-2942-48ba-afb8-e4b23a98767b.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
issue fixed
