### ISSUE TITLE
Logo: Redirect to the main site

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#53]
Description:

Since the HK vitals blog is a part of the HK Vitals site, On clicking the logo one should get redirected to the home page of the main site like how it is happening on TB blog. 

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157868772-6beb80e1-a991-49e2-a7fe-0bdf69a81d38.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Issue fixed
