### ISSUE TITLE
Latest and Trending articles: Keep the excerpt up to 3 lines 

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#54]
Description:
The excerpt for the articles in this section should be up to 3 lines

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157869756-f3c634d6-d491-469e-81b1-d38db8d4391f.png)

Ref site:
![image](https://user-images.githubusercontent.com/75774252/157869793-d0d169f6-f79a-4bf0-8349-9b50b255646c.png)

**Comment by ShivaniAjency** [comment]
Issue fixed

**Comment by mrnarvekar** [comment]
Done. Kindly recheck
