### ISSUE TITLE
Mobile: Footer: cash on delivery icon looks blurry

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#56]
Description:
Cash on deliver icon looks blurry on the site

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157872874-0f79a390-f06c-4622-a30d-fe56f89b0788.png)

**Comment by mrnarvekar** [comment]
This is not an issue. The COD image which is there in the design gets cut on the website and hence we have used cod image from design in png format. This is the reason why the image looks blur.

**Comment by ShivaniAjency** [comment]
Is there any solution to this? @mrnarvekar

**Comment by ShivaniAjency** [comment]
@EktaNaik Can we ask the client for the same?

**Comment by EktaNaik** [comment]
@ShivaniAjency Yes, we'll need to ask client for a correct svg image for this icon.
@mrnarvekar Please email Aman about it in tomorrow's email. Also remind to discuss this on call tomorrow.

**Comment by mrnarvekar** [comment]
Issue resolved. Kindly check

**Comment by ShivaniAjency** [comment]
issue fixed
