### ISSUE TITLE
Tab: Single blog post: No space between the last paragraph and the author

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#57]
Description:
There is no proper space between the last paragraph and the author's name

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157876749-f652479e-1daa-477d-b708-087bb54886be.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Issue fixed
