### ISSUE TITLE
Search bar: Suggested articles box

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#58]
Description:

- Alignment of the search box is improper
- The box width is a little extra on the site. 
- The width should be 240 as per the reference site

Screenshot:
Ref site:
![image](https://user-images.githubusercontent.com/75774252/158155314-27c6a4a3-7437-4099-a14e-62b74cf4ceb9.png)

Our site:
![image](https://user-images.githubusercontent.com/75774252/158155373-fae99f29-c2be-4189-9763-72ace75c234a.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
Please check the alignment of the suggested articles box

**Comment by mrnarvekar** [comment]
This is not an issue. Dropdown container must display inside the main container of the search functionality. Checked the same in the plugins documentation. Refer below screenshot and we can see that dropdown shows inside the search container
![image](https://user-images.githubusercontent.com/89069801/158328180-7413e12c-5160-4f9f-a4be-73c3db85c746.png)

**Comment by ShivaniAjency** [comment]
Noted
