### ISSUE TITLE
Subscribe to our newsletter: Incorrect button text

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#59]
Description:

- The text on the button should be sign up as per the ref site

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/158159085-cbb2dddf-3e67-4b18-82ee-8c58f6a43fde.png)

Ref site
![image](https://user-images.githubusercontent.com/75774252/158159137-651e8120-43e9-4e19-a5fb-eb77290e697a.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
issue fixed

**Comment by ShivaniAjency** [comment]
Please check the gap between the button and the end of the container

**Comment by ShivaniAjency** [comment]
issue fixed
