### ISSUE TITLE
Latest & Trending articles: Image should cover the entire column

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/HKVitals-Blog#9]
Description:

The image should be covering the entire column

Screenshot:
1) Site
![image](https://user-images.githubusercontent.com/75774252/156363126-f1d0663a-9a1b-4799-a74a-1180fc08ade4.png)

2) Reference site:
![image](https://user-images.githubusercontent.com/75774252/156363227-27158587-38c6-42c7-88f9-422c1d33b4a3.png)

**Comment by mrnarvekar** [comment]
Done. Kindly check

**Comment by ShivaniAjency** [comment]
solved
